#!/usr/bin/env python3
import re
import sys
from pathlib import Path

VAR_REGEX = re.compile(
  r'^(\s*)(?:export\s+)?(const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*=\s*(["\'])(TODO_EDIT(?:_[A-Z0-9_]+)?)\4\s*;?',
  re.MULTILINE
)

PROP_REGEX = re.compile(
  r'^(\s*)([A-Za-z_$][A-Za-z0-9_$]*)\s*:\s*(["\'])(TODO_EDIT(?:_[A-Z0-9_]+)?)\3\s*(,?)',
  re.MULTILINE
)

def env_name(marker: str, fallback: str) -> str:
  return fallback.upper() if marker == "TODO_EDIT" else marker.replace("TODO_EDIT_", "", 1)

def make_env_read(name: str) -> str:
  return f'(typeof __ENV["{name}"] !== "undefined" ? __ENV["{name}"] : "")'

def replace_vars(text: str, envset: set) -> str:
  def _r(m):
      indent, decl, var_name, quote, marker = m.groups()
      e = env_name(marker, var_name)
      envset.add(e)
      return f'{indent}{decl} {var_name} = {make_env_read(e)};'
  return VAR_REGEX.sub(_r, text)

def replace_props(text: str, envset: set) -> str:
  def _r(m):
      indent, key, quote, marker, comma = m.groups()
      e = env_name(marker, key)
      envset.add(e)
      return f'{indent}{key}: {make_env_read(e)}{comma}'
  return PROP_REGEX.sub(_r, text)

def main():
  if len(sys.argv) < 2:
      sys.exit(1)

  in_path = Path(sys.argv[1])
  out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(sys.argv[1])

  if not in_path.exists():
      sys.exit(1)

  source = in_path.read_text(encoding="utf-8")
  envset = set()

  transformed = replace_vars(source, envset)
  transformed = replace_props(transformed, envset)

  banner = f'// Auto-generated by k6_envize.py\n// ENV vars: {", ".join(sorted(envset)) if envset else "(none)"}\n\n'
  if not transformed.startswith("// Auto-generated"):
      transformed = banner + transformed

  out_path.write_text(transformed, encoding="utf-8")
  
  if envset:
      sample_path = in_path.parent / ".env.example"
      sample_lines = "\n".join(f"export {v}=\"\"" for v in sorted(envset))
      sample_path.write_text(sample_lines + "\n", encoding="utf-8")

if __name__ == "__main__":    
  main()